project: 
  type: website
  output-dir: docs

website: 
  title: "Sajad's Portfolio"
  navbar:
    left: 
      - Home.qmd
      - Experiences.qmd
      - Publications.qmd
      - Skills.qmd
      - Honors.qmd
      - Contact.qmd
      - Projects.qmd


format:
  html:
    theme: jolla
    css: styles.css
    toc: true
    extras: 
      - "favicon.ico"
      - "profile.jpg"
