---
title: "Publications"
format: html
editor: visual
---

## Publications

For a full list of publications, visit my [Google Scholar profile](https://scholar.google.com/citations?user=RtCQl78AAAAJ&hl=en).

### Journal Papers

-   S. Kargar, Z. Baniamerian, JL. Moran, "Molecular dynamics calculations of the enthalpy of vaporization for different water models," J. Mol. Liq. 393 (2023) 123455.
-   S. Kargar, A. Moosavi, "Bidirectional water transport through non???straight carbon nanotubes," J. Mol. Liq. 276 (2019) 39--46.
-   A. Reihani, A. Soleimani, S. Kargar, V. Sundararaghavan, A. Ramazani, "Graphyne Nanotubes: Materials with Ultralow Phonon Mean Free Path and Strong Optical Phonon Scattering for Thermoelectric Applications," J. Phys. Chem. C. 122 (2018) 22688--22698.

### Patents

-   M. Karimi, Sh. Fazeli Panah, S. Kargar, "Skin heat exchanger," App No: US 62/884, 802, USA, 2019.
-   M. Karimi, Sh. Fazeli Panah, S. Kargar, "Compact rotary heat-exchanger," App No: US 63/312, 159, USA, 2022.

### Conference Proceedings

-   S. Kargar, JL Moran, "Analyzing the phase-change of water molecules at the nanoscale using molecular dynamics," Presented, 2023 Mason Graduate Interdisciplinary Conference, Fairfax, VA, USA, Mar. 2023.
-   JL. Moran, A. Chandra, W. Peng, P. Keblinski, S. Kargar, "Potential of Active Particles for Heat Transfer Enhancement," Presented, APS Division of Fluid Dynamics Meeting Abstracts, Arizona, USA, Nov. 2021.
-   S. Kargar, A. Moosavi, Z. Baniamerian, R. Mehdipour, "Numerical simulation of viscous flows by smoothed particle hydrodynamics", Presented, ISME, Tehran, Iran, May. 2020.
-   S. Kargar, A. Moosavi, J. Kargar, M Irani???Rahaghi, "Transport behavior of a protein in carbon nanotubes", Presented, ICNS8, Tehran, Iran, Apr. 2020.
-   S. Kargar, Z. Baniamerian, R. Mehdipour, "Desalination Using Nanoporous Graphene", Presented, ICNS8, Tehran, Iran, Apr. 2020.
-   S. Kargar, J. Kargar, M. Karimi, A. Moosavi, "Molecular dynamics simulations of lithium???ion batteries at high temperatures", Presented, ICNS8, Tehran, Iran, Apr. 2020.
-   S. Kargar, A. Soleimani, A. Moosavi, "Molecular Dynamic Simulations of Lithium Cobalt Oxide Cathode Materials", Presented, ICNS7, Tehran, Iran, Feb. 2018.
-   S. Kargar, A. Ghanbari, A. Moosavi, Z. Seyedraoufi, "Simulation of Flow $Ni-P-Al_{2}O_{3}-TiO_{2}$ nano composite coating by Prediction (ANN)", Presented, ICNS7, Tehran, Iran, Feb. 2018.
-   A. Ghanbari, S. Kargar, J. Kargar "Investigation of thermal conductivity of silicon nanowires using molecular dynamics", Presented, ICNS7, Tehran, Iran, Feb. 2018.
-   J. Kargar, S. Kargar, N. Hadian, A. Ghanbari "Investigation of Single Wall Carbon Nanotubes (SWCNTs) Mechanical Properties", Presented, ICNS7, Tehran, Iran, Feb. 2018.
-   A. Ghanbari, S, Kargar, "Preparation of $Ni-P-Al_{2}O_{3}-TiO_{2}$ Nano composite coating by Electroless", Presented, ICNS7, Tehran, Iran, Feb. 2018.
-   A. Soleimani, M.R. Zamani???Kouhpanji, M. Ghorbanzadeh, S. Kargar "Molecular dynamic simulations of Lithium Cobalt Oxide cathode materials", Presented, LAMMPS Workshop and Symposium, Sandia National Laboratories, New Mexico, United States, Aug. 2017.
-   A. Ghanbari, S. Kargar, "Simulation of Flow EN Nanocomposite Coating by Prediction (ANN)", Presented, ICNS6, Kish Island, Iran, Mar. 2016.
-   S. Kargar, A. Moosavi, "The Effect of Bending Angle on the Fluid Flow in Carbon Nanotubes", Presented, ICNS6, Kish Island, Iran, Mar. 2016.
-   S. Kargar, A. Moosavi, "Thermo???mechanical Properties of Silicon Nanowires Using Molecular Dynamics Simulation", Presented, 4th Nano Today Conference, Dubai, United Arab Emirates, Dec. 2015.
